[package]
name = "webpage"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "webpage"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

webpage_integrity = { workspace = true } 
